language: java
dist: trusty

addons:
    sonarcloud:
        organization: "bogdan"
        token:
           secure: "d5988687b8c53619a9a83cc65e0963e90ff86805"
            
jdk:
  - oraclejdk8
  
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=test_GreenCity1 -DskipTests=true
