language: java
dist: trusty

addons:
    sonarcloud:
        organization: "bogdan"
        token:
            secure: "1367ab99c7cac16bdd499839ed772ac06c0592cd"
            
jdk:
  - oraclejdk8
       
# script:
#   # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Bogdan-Kuzenko_GreenCity -DskipTests=true
